theme: jekyll-theme-slate

# Dependencies
#markdown:         kramdown
#highlighter:      rouge

# Permalinks
#permalink:        pretty

# Setup
title:            'Integration Tests'
tagline:          'The GAP Package Distribution'
description:      'hopefully this shows test results somehow and at some point'

#exclude: 
#    - "LICENSE.hyde.md"
#    - "README.hyde.md"
#    - "program.aux"
#    - "program.log"
#    - "program.out"
#    - "program.tex"
#    - "misc"